/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloBuffer */

#ifndef _Included_HelloBuffer
#define _Included_HelloBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloBuffer
 * Method:    initc
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_HelloBuffer_initc
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
