version: '3'
services:

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=profiles
    volumes:
      - ./init/mongo:/docker-entrypoint-initdb.d

#  zookeeper:
#    image: "confluent/zookeeper"
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: "confluent/kafka"
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=localhost
#    links:
#      - zookeeper
