name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11 ]
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build the chapter-specific examples
      run: ./gradlew build-chapters --refresh-dependencies
      shell: bash
    - name: Build the part2 10k steps challenge application
      run: ./gradlew build-part2-steps-challenge --refresh-dependencies
      shell: bash
